import { getCssText } from '@/styles/styles'
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <meta name="description" content="Generated by create next app" />

                <link
                    href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;600&family=Inter:wght@400;500;600;700&display=swap"
                    rel="stylesheet"
                />
                <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
                <link rel="icon" type="image/png" sizes="48x48" href="/favicon.png" />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}
